package com.example.rising_test_yanolja.src.main.home.internalRoom

import com.example.rising_test_yanolja.R
import com.example.rising_test_yanolja.config.BaseFragment
import com.example.rising_test_yanolja.databinding.FragmentHomeEnjoyBinding
import com.example.rising_test_yanolja.databinding.FragmentHomeInternalRoomBinding
import com.example.rising_test_yanolja.databinding.FragmentMyNearBinding
import com.example.rising_test_yanolja.databinding.FragmentMyYanoljaBinding

class HomeInternalRoomFragment : BaseFragment<FragmentHomeInternalRoomBinding>(FragmentHomeInternalRoomBinding::bind, R.layout.fragment_home_internal_room) {
}